<a href="https://colab.research.google.com/github/shreyagopal/AI-Cybersecurity-DSCI-6672/blob/master/Perceptron_for_Phish_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Perceptron for Phish Detection**

**Task:** Train a single-layer perceptron model to create a phish detector. You will use the Phishing Website dataset ( https://archive.ics.uci.edu/ml/datasets/phishing+websites ) for training and evaluating your model. The description of features can be found in the Data Folder.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Creating dataframe for the phishing dataset
df = pd.read_csv('phishing_dataset.csv',header = None)
df

       0   1   2   3   4   5   6   7   8   ...  22  23  24  25  26  27  28  29  30
0      -1   1   1   1  -1  -1  -1  -1  -1  ...   1  -1  -1  -1  -1   1   1  -1  -1
1       1   1   1   1   1  -1   0   1  -1  ...   1  -1  -1   0  -1   1   1   1  -1
2       1   0   1   1   1  -1  -1  -1  -1  ...   1   1  -1   1  -1   1   0  -1  -1
3       1   0   1   1   1  -1  -1  -1   1  ...   1  -1  -1   1  -1   1  -1   1  -1
4       1   0  -1   1   1  -1   1   1  -1  ...   1  -1  -1   0  -1   1   1   1   1
...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..
11050   1  -1   1  -1   1   1   1   1  -1  ...  -1   1   1  -1  -1   1   1   1   1
11051  -1   1   1  -1  -1  -1   1  -1  -1  ...   1   1   1   1   1   1  -1   1  -1
11052   1  -1   1   1   1  -1   1  -1  -1  ...   1   1   1   1  -1   1   0   1  -1
11053  -1  -1   1   1   1  -1  -1  -1   1  ...   1   1   1   1  -1   1   1   1  -1
11054  -1  -1   1   1   1  -1  -1  -1   1  ...   1  -1   1  -1  -1  -1   1  -1  -1

[11055 rows x 31 columns]

In [2]:
# Creating target & sample variables

y = df.iloc[:, 30].values
X = df.iloc[:, :30].values
y.shape, X.shape

((11055,), (11055, 30))

In [3]:
# Splitting the data into train and test datasets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
         X, y, test_size=0.2, random_state= 12) 
X_test.shape, X_train.shape

((2211, 30), (8844, 30))

In [5]:
# Fitting the train data to perceptron model
from sklearn.linear_model import Perceptron

p = Perceptron(max_iter=5000, eta0=0.0003, random_state=4)
p.fit(X_train, y_train)

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=0.0003,
           fit_intercept=True, max_iter=5000, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=4, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [0]:
# Predicting the target value for the test dataset

y_pred = p.predict(X_test)

In [7]:
# Calculating accuracy and number of mispredicted samples

from sklearn.metrics import accuracy_score

print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.5f' % accuracy_score(y_test, y_pred))

Misclassified samples: 162
Accuracy: 0.92673

* max_iter - No dependency.
* validation_fraction - No dependency